APT::FTPArchive::Release::Origin "listrrise";
APT::FTPArchive::Release::Label "listrrise";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Version "1.0";
APT::FTPArchive::Release::Codename "ios";
APT::FTPArchive::Release::Architectures "iphoneos-arm iphoneos-arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "listrrise repo (dinapenis, iOS 12-15)";
