TWEAK_NAME = DinaPenis

DinaPenis_FILES = Tweak.xm
DinaPenis_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
DinaPenis_FRAMEWORKS = UIKit QuartzCore MediaPlayer CallKit CoreGraphics

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
