BUNDLE_NAME = DinaPenisPrefs

DinaPenisPrefs_FILES = DinaPenisPrefs.mm
DinaPenisPrefs_CFLAGS = -fobjc-arc
DinaPenisPrefs_FRAMEWORKS = UIKit
DinaPenisPrefs_PRIVATE_FRAMEWORKS = Preferences
DinaPenisPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
