TWEAK_NAME = DinaWidgets

DinaWidgets_FILES = Widgets.xm
DinaWidgets_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
DinaWidgets_FRAMEWORKS = UIKit QuartzCore MediaPlayer

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
